### ISSUE TITLE
what is the use of 'trail' ?

### ISSUE THREAD

**Issue by splaisan** [cghdev/owncloud-dl#6]
I finally made it to create a working configuration file but the variable 'trail' escapes me.
What is trail intended for?

my config file is now like

```
username=secret
password=azertyuiop
host=https://nextcloud.host.com/
trust_cert=yes
trail=
path=remote.php/webdav/MainFolder/
```

MainFolder is a folder on the root of the server where all should be stored and I do not wish to use it in my commands (it should be implicit).
All works now nicely except when I want to create a link for which I need to specify /MainFolder/<thefolder_to_share> instead of only <thefolder_to_share>
Deleting by contrast works by providing <thefolder_to_share> with -D directly

Thanks for your feedback
S

**Comment by cghdev** [comment]
I'll be honest with you... I don't remember what's $trail for. Probably some edge case I thought of, or just needed for some old version. I'll review it and remove it if not needed.

The reason why you need to specify "/MainFolder/" when you create a link, is because there are certain tasks use the OCS API instead of webdav.
OCS API has a different url (that's why in the config file host= and path= are two different variables, because host= is used for the OCS API too). At the moment, the only cloud-dl options using the OCS API are the related with sharing files (share, unshare, list shares), the rest is using webdav (including deleting files)

**Comment by splaisan** [comment]
Thanks for you info. I added a couple of functions to share from scripts and to return the size of files in a share. If you feel these could be usefull, i ll be happy to contribute but do not know the procedure as i am not expert in git work

**Comment by cghdev** [comment]
Feel free to fork the project, make any changes and make a pull request

**Comment by splaisan** [comment]
thanks, I close this now :-)

**Comment by splaisan** [comment]
I found it -:)
for a server like 'https://example.com/nextcloud'
trail=nextcloud

leading to a conf file of the kind:

```
username=1234
password=AZERTYUIOP
host=http://my.server.ip/nextcloud
trust_cert=yes
trail=nextcloud
path=remote.php/webdav
```

note that nextcloud is both in host and trail, it took me minutes before I finally ran --configure and discover this
